conf/application.conf

AFID-37 upgraded assest frontend

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employments_main.scala.html
conf/messages

AFID-107: Update page inline with prototype.

---

conf/messages

Title pretty much covers it...

AFID-224 Changed 'PAYE' to 'income' for the not_authorised error view.

---

app/utils/Currency.scala
test/utils/CurrencySpec.scala

AFID-268 Update 3 data items frontend to match latest design
Treat zero as positive in currency formatting.

[AFID-268][CR] Update 3 data items frontend to match latest design

---

conf/messages

Added the full stop to the employmenthistory.tax-account.caveat.text file

[AFID-268][AS] Update 3 data items frontend to match latest design

---

app/controllers/BaseController.scala
test/connectors/CitizenDetailsConnectorSpec.scala
test/connectors/TaxHistoryConnectorSpec.scala
test/controllers/BaseControllerSpec.scala
test/controllers/ClientErrorControllerSpec.scala
test/controllers/EmploymentDetailControllerSpec.scala
test/controllers/EmploymentSummaryControllerSpec.scala
test/controllers/SelectTaxYearControllerSpec.scala
test/models/PersonSpecs.scala
test/resources/json/model/api/personDeceasedFalse.json
test/resources/json/model/api/personDeceasedNoValue.json
test/resources/json/model/api/personDeceasedTrue.json
test/support/fixtures/Fixtures.scala
test/support/fixtures/PersonFixture.scala
test/views/taxhistory/employment_detailSpec.scala
test/views/taxhistory/employment_summarySpec.scala

Updated deceased flag to be optional, and added/edited unit tests.

[AFID-270][AS] Update deceased flag to be optional

---

app/config/FrontendAppConfig.scala
app/controllers/ClientErrorController.scala
app/controllers/auth/AgentAuth.scala
app/views/errors/no_agent_services_account.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/BaseControllerSpec.scala
test/controllers/ClientErrorControllerSpec.scala
test/views/errors/no_agent_services_accountSpec.scala

Fixed redirect links for Agents Not Subscribed

[Afid-274][CR,AS]

---

conf/messages

Text changed to be in line with rest of the application

[AFID-274][AS] - Fix back link on enter nino page & login error handling

---

app/controllers/BaseController.scala
app/controllers/ClientErrorController.scala
app/controllers/EmploymentDetailController.scala
app/controllers/EmploymentSummaryController.scala
app/controllers/SelectClientController.scala
app/controllers/SelectTaxYearController.scala
app/utils/TaxHistoryLogger.scala

Extended logging and cleaned up some syntax warnings.

[AFID-272][CR] Review error handling and logging - Frontend

---

app/controllers/EmploymentSummaryController.scala
test/controllers/EmploymentSummaryControllerSpec.scala

Return an empty list when allowance not found in getTaxHistory instead of trying to parse empty JSON

[AFID-284] Allowances JSON response is null

---

app/views/taxhistory/employment_summary.scala.html
conf/application.conf
conf/messages
test/views/taxhistory/employment_summarySpec.scala

removed message
removed column,
reformatted dates

[AFID-306] Update UI for "Underpaid tax and debts"

---

test/views/taxhistory/select_tax_yearSpec.scala

[AFID-287 ] Display Client Name in Screen

---

app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html
test/controllers/EmploymentDetailControllerSpec.scala

added ID's to elements requested

[AFID-285] Request for IDs to be added to elements

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html

The two pages are the same, so fixing one ticket will fix the other.

[AFID-296] [AFID-297] Accessibility review - Employment record & Pension record

---

app/views/taxhistory/employment_summary.scala.html

[Afid-295] 
AFID 295 got rid of html errors and warnings

[AFID-295] Accessibility review - Client income record

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/select_tax_year.scala.html

[AFID-294] Added hidden legend to select tax year

[AFID-294] Accessibility review - Select tax year

---

app/views/taxhistory/select_client.scala.html
test/views/taxhistory/select_clientSpec.scala

[AFID-292] added legend and removed some html warnings

[AFID-292] Accessibility review - Select client inc. error states

---

app/views/taxhistory/select_client.scala.html

[AFID-354] Changed headings tag, and reformatted errorSummary

[AFID-354] Accessibility review - Error and Validation (All pages)

---

app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html

[AFID-356] added ids to html objects

[AFID-356] Add IDs to the following elements

---

app/controllers/EmploymentSummaryController.scala
app/model/api/EmploymentStatus.scala
app/utils/StringUtils.scala
app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html
test/utils/StringUtilsSpec.scala

Render unkown dates for employments with unkown status and missing dates

[Afid 363] - View Employment for the full tax year - including 'no data' periods

---

app/controllers/EmploymentSummaryController.scala
app/models/taxhistory/Person.scala
app/utils/ControllerUtils.scala
app/utils/StringUtils.scala
app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html
conf/messages
test/utils/ControllerUtilsSpec.scala
test/views/taxhistory/employment_summarySpec.scala
test/views/taxhistory/testDataConstants.scala

Added None option for view record

[AFID-363] View Employment for the full tax year - including 'no data' periods

---

app/views/taxhistory/employment_detail.scala.html
conf/messages
test/views/taxhistory/employment_detailSpec.scala

[AFID-376] Deleted payments description form view, messages, and tests

[AFID-376] Remove Payments descriptive text from Pension Detail page

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_summary.scala.html
conf/messages
test/views/taxhistory/employment_summarySpec.scala

[AFID-315] Modified text and styling of Underpaid Tax and Debts table

[AFID-315] Amend phrasing for Underpaid Tax and Debts on Client Income Record

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html
conf/messages
test/views/taxhistory/employment_detailSpec.scala

[AFID-358] now shows text instead of empty table when there are no deductions

[AFID-358] CY pension details page

---

app/utils/ControllerUtils.scala
app/views/taxhistory/employment_detail.scala.html
test/utils/ControllerUtilsSpec.scala

[Afid-343] Changed description of allowances and deductions to sentence case

[Afid-343] CY employment details page

---

app/config/AppConfig.scala
app/controllers/EmploymentDetailController.scala
app/modules/LocalGuiceModule.scala
conf/application.conf
test/views/TestAppConfig.scala

[AFID-433] added feature flag for student loans

[AFID-433] Feature Flags

---

app/views/taxhistory/employment_summary.scala.html
conf/messages
test/views/taxhistory/employment_summarySpec.scala
test/views/taxhistory/testDataConstants.scala

[AFID-409] added alternate text when there are no private pensions

[AFID-409] No pension records message

---

app/views/taxhistory/employment_summary.scala.html
conf/messages
test/views/taxhistory/employment_summarySpec.scala

section from being displayed for CY

[AFID-410] Added No allowances message

---

app/views/taxhistory/employment_detail.scala.html
conf/messages
test/views/taxhistory/employment_detailSpec.scala
test/views/taxhistory/testDataConstants.scala

{AFID-412] added alternate text for an employments with no company benefits

[AFID-412] No company benefits for an employment message

---

app/views/taxhistory/employment_detail.scala.html

[AFID-435] added id's to elements in employment detail

[AFID-435] Please add IDs to the following Elements

---

app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/select_tax_year.scala.html

Changed business logic regarding when to show company benefits

[AFID-437] Fix Business logic according to Google Sheet

---

app/views/taxhistory/select_tax_year.scala.html

[AFID-421] Removed spacing between heading and radio buttons

[AFID-421] Select tax year: Tighten up spacing around header and radio buttons

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html

[AFID-424] reformatted tax code

[AFID-424] Layout of tax code breakdown 

---

app/views/taxhistory/select_tax_year.scala.html
conf/messages
test/views/taxhistory/select_tax_yearSpec.scala

[AFID-414] added side bar with links to select Tax year

[AFID-414] Navigation sidebar on select tax year

---

app/views/taxhistory/employment_summary.scala.html
app/views/taxhistory/select_tax_year.scala.html
conf/messages
test/views/taxhistory/employment_summarySpec.scala

[AFID 415]  added side-bar links and headings to emplyment summary page

[AFID 415] Navigation sidebar on income record summary page

---

app/controllers/BaseController.scala
app/controllers/ClientErrorController.scala
app/controllers/EmploymentSummaryController.scala
app/controllers/SelectTaxYearController.scala
app/views/errors/no_data.scala.html
conf/app.routes
test/controllers/BaseControllerSpec.scala
test/controllers/ClientErrorControllerSpec.scala
test/controllers/EmploymentSummaryControllerSpec.scala
test/views/errors/no_dataSpec.scala

[AFID-448] added name, nino, and dates to no data error page

[AFID-448] Updates to "No data" error page

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_summary.scala.html
app/views/taxhistory/select_client.scala.html
app/views/taxhistory/select_tax_year.scala.html

Got rid of validation errors and warnings, barring the 10 warnings that we inherit.

[AFID-295]  Accessibility review - Client income record

---

app/views/taxhistory/employment_detail.scala.html

[AFID-296] reformated employment detail to ensure less html warnings and errors

[AFID-296] Accessibility review - Client income record

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html
conf/messages
test/views/taxhistory/employment_detailSpec.scala

reformatted tax code breakdown and added total amounts

[AFID-453 and 430]  tax code breakdown

---

app/views/taxhistory/employment_detail.scala.html

[AFID-452] made payments aligned to the right

[AFID-452] Align taxable income, Income Tax and student loan payment amounts right

---

conf/messages

amended text to include missing word

[AFID-453] Add sub-totals to allowances and deductions in tax code breakdown

---

app/assets/stylesheets/taxhistory.scss
app/controllers/ClientErrorController.scala
app/views/errors/not_authorised.scala.html
conf/messages
test/views/errors/not_authorisedSpec.scala

added nino for not authorized page, and changed text

[AFID-445] Content changes to "Not authorised" error page

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_summary.scala.html

changed spacing in allowance table

[AFID-451] Update on allowances (EYA) again

---

app/views/taxhistory/employment_detail.scala.html

altered ID's to avoid duplicates

[AFID-296] Accessibility review - Employment record

---

app/views/taxhistory/employment_detail.scala.html

[AFID-256]  Company Benefits missing ID, in QA

---

app/views/taxhistory/employment_detail.scala.html

wrapped company benefits in if statement so the header should never appear for current year

[AFID-458]     Company Benefits appearing in CY

---

app/views/taxhistory/employment_detail.scala.html

re-factored if statements regarding company benefits

[AFID-458] Company Benefits appearing in CY

---

app/views/taxhistory/employment_summary.scala.html
test/views/taxhistory/employment_summarySpec.scala

make sure underpaid tax tab only appears for cy-1

[AFID-454] Message for underpaid taxes and debts

---

app/utils/Currency.scala
test/utils/CurrencySpec.scala

Fixed currency so that numbers with one decimal place will be formated with 2

[AFID-459] All monetary values should have two decimal places or no decimal places

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html

added thick blue line and got rid of thin line only on mobile

[AFID-461] Add a blue separator above the navbar for detail record pages

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
build.sbt
project/plugins.sbt

can't do rest due to play 2.6 upgrade required

DDCE-474: updated dependacies

---

build.sbt

Disabled plugin JUnitXMLReportPlugin. It was causing instability when deploying this service.

[RS][DDCE-623] Disabled JUnit XML report plugin.

---

app/ErrorHandler.scala
app/config/AppConfig.scala
app/controllers/ClientErrorController.scala
app/views/errors/not_authorised.scala.html
test/views/TestAppConfig.scala
test/views/errors/not_authorisedSpec.scala

Issue was found with the usage of the ServicesConfig getString method for assigning to a boolean isDevEnv variable. The method attempted to find a config string, but in case of it not existing, it threw an exception. This resulted in failed tests. The variable was found to be unnecessary, and all occurrences of the isDevEnv variable in if statements were replaced to use its 'false' route.
- Were there …

[RS][DDCE-623] Removed isDevEnv variable.

---

app/config/AppConfig.scala
app/views/govuk_wrapper.scala.html
conf/application.conf
test/views/TestAppConfig.scala

##New feature 
Added code for IRV Google Tag Manager (GTM) Migration
Related PR which needs to be merged before merging this PR:
https://github.com/hmrc/app-config-staging/pull/6348

DDCE-1058 Added GTM code

---

conf/application.conf

Updated CSP policy to work on staging.
Related CR, which should be merged before this:
https://github.com/hmrc/app-config-staging/pull/6383

DDCE-1058 Updated CSP policy

---

conf/application.conf

Updated config with new GTM container id.

[EH][DDCE-1315] Changed GTM container

---

test/views/error_templateSpec.scala
test/views/errors/deceasedSpec.scala
test/views/errors/mci_restrictedSpec.scala
test/views/errors/no_agent_services_accountSpec.scala
test/views/errors/no_dataSpec.scala
test/views/errors/not_authorisedSpec.scala
test/views/errors/technical_errorSpec.scala
test/views/taxhistory/employment_detailSpec.scala
test/views/taxhistory/employment_summarySpec.scala
test/views/taxhistory/select_clientSpec.scala
test/views/taxhistory/select_tax_yearSpec.scala

DDCE-1617: Implement cookies consent banner for tax-history-frontend

---

app/views/taxhistory/employment_detail.scala.html
test/views/taxhistory/employment_detailSpec.scala

[DDCE-1553]:Tax-history-frontend GOV.UK libraries and Play 2.7 upgrade

---

app/ErrorHandler.scala
build.sbt
project/AppDependencies.scala
project/plugins.sbt

Tax-history-frontend Bootstrap Upgrade for Auth Client v5.6.0

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/controllers/ClientErrorControllerSpec.scala
test/controllers/EmploymentSummaryControllerSpec.scala
test/support/BaseSpec.scala
test/support/CallOpsSpec.scala
test/views/Fixture.scala

Play 2.8 bootstrap upgrade

---

app/ErrorHandler.scala
app/controllers/ClientErrorController.scala
app/views/taxhistory/employment_summary.scala.html
conf/application.conf
conf/messages
project/AppDependencies.scala
run_all_tests.sh

Screenshot showing the inspection of the HTML changes in the screen
Update:
Review missing change of `Early Years Adjustment (EYA)`  in table cell text

DDCE-2948 - IRV (A) Issue details is placed in the table element issue identified in DAC report

---

app/controllers/BaseController.scala
app/controllers/EmploymentDetailController.scala
app/controllers/EmploymentSummaryController.scala
app/controllers/SelectTaxYearController.scala
run_all_tests.sh
test/controllers/BaseControllerSpec.scala
test/controllers/EmploymentDetailControllerSpec.scala
test/controllers/SelectTaxYearControllerSpec.scala

DDCE-hotfix-1 error level log change

---

run.sh

temp run.sh for correct AAC version

---

app/config/AppConfig.scala
app/controllers/EmploymentSummaryController.scala
app/controllers/SignedOutController.scala
app/views/govuk_wrapper.scala.html
app/views/taxhistory/SignedOut.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/EmploymentSummaryControllerSpec.scala
test/controllers/SignedOutControllerSpec.scala
test/model/api/TotalIncomeSpec.scala
test/views/taxhistory/SignedOutViewSpec.scala

Summary:  Included the timeout dialogue functionality. 

DDCE-2933 : IRV (A) No timeout dialogue identified in DAC report

---

app/views/errors/no_data.scala.html
app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html
app/views/taxhistory/select_tax_year.scala.html
conf/messages
test/model/api/TotalIncomeSpec.scala
test/views/errors/no_dataSpec.scala
test/views/taxhistory/employment_detailSpec.scala
test/views/taxhistory/employment_summarySpec.scala
test/views/taxhistory/select_tax_yearSpec.scala

DDCE-2967:IRV meta title fix

---

app/views/taxhistory/employment_summary.scala.html
conf/messages.cy
conf/messages.en
test/views/taxhistory/employment_summarySpec.scala

DDCE-2958:Allowances inset text

---

app/FrontendModule.scala
app/controllers/BaseController.scala
app/views/govuk_wrapper.scala.html
app/views/taxhistory/employment_summary.scala.html
project/AppDependencies.scala
project/plugins.sbt

Fixes for : 
https://github.com/hmrc/accessibility-audits-external/issues/4294, 
English <img width="302" alt="Screenshot 2022-08-17 at 11 57 28" src="https://user-images.githubusercontent.com/369407/185102316-e24730fe-9fc6-4a50-8ece-c5e3a8429992.png">  Welsh  <img width="353" alt="Screenshot 2022-08-17 at 11 57 21" src="https://user-images.githubusercontent.com/369407/185102323-573c9d96-5d1f-4fb9-8d93-5b056b73143e.png">
https://github.com/hmrc/accessibility-audits-external/issues/4293

DDCE-3275 - IRV (A) issues identified in DAC Report

---

app/views/taxhistory/select_client.scala.html
app/views/taxhistory/select_tax_year.scala.html

##Bug fix 
When Welsh lang is selected, the visually hidden error text needs to be translated to Welsh too.

DDCE-DAC-WelshError : Show visually hidden error text in welsh

---

app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html
project/plugins.sbt
test/views/taxhistory/employment_detailSpec.scala

DDCE-3003 Remove status from employment details view

---

conf/messages.cy
conf/messages.en
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/views/taxhistory/select_clientSpec.scala

Welsh content update to match translation from welsh team.
https://jira.tools.tax.service.gov.uk/browse/DDCE-3011
ATs --> https://github.com/hmrc/tax-history-acceptance-tests/pull/158
[DDCE 3004-010-011-012-013 - Welsh Translation .xlsx](https://github.com/hmrc/tax-history-frontend/files/9878555/DDCE.3004-010-011-012-013.-.Welsh.Translation.xlsx)

DDCE-3011 Update select client content

---

app/views/errors/no_data.scala.html
app/views/helpers/p.scala.html

##Bug fix
tax-history-accessibility-tests have been failing since early 2021. There're a total 14 failures cause of a) an additional comma introduced as part of a change introduced in 2021 b) two web elements on one of the pages has same value assigned to id attribute. Both of them have been fixed in this PR, a) fixing the typo b) assigning a unique-id to the web element. I have tested these changes by:
1. running accessibility tests on tax-history-acceptance-tests repo which is used to first run the tests to capture relevant assets (html, js, css etc) for accessibility assessment - this has successfully generated the same set of errors reported on Jenkins build
2. make necessary changes as described above
3. running the tests locally on the repo tax-history-frontend
4. running …

DDCE-3414: Fix accessibility issues

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html
test/views/taxhistory/employment_detailSpec.scala

Added `<dl>` tags to the issued tax code.
Reorganised CSS for the taxcode.

DDCE-3001: Accessibility change for taxcode description tags

---

app/controllers/ConfirmDetailsController.scala
app/views/taxhistory/confirm_details.scala.html
app/views/taxhistory/select_tax_year.scala.html
build.sbt
conf/app.routes
conf/application.conf
conf/messages.cy
conf/messages.en
export-versions-for-it-tests
project/AppDependencies.scala
project/plugins.sbt
test/connectors/CitizenDetailsConnectorSpec.scala
test/connectors/TaxHistoryConnectorSpec.scala
test/controllers/BaseControllerSpec.scala
test/controllers/ClientErrorControllerSpec.scala
test/controllers/ConfirmDetailsControllerSpec.scala
test/controllers/EmploymentDetailControllerSpec.scala
test/controllers/EmploymentSummaryControllerSpec.scala
test/controllers/SelectClientControllerSpec.scala
test/controllers/SelectTaxYearControllerSpec.scala
test/controllers/SignedOutControllerSpec.scala
test/support/BaseSpec.scala
test/views/taxhistory/ConfirmDetailsViewSpec.scala

DDCE-3012 Added New client confirmation screen + a bit of cleanup

---

app/views/govuk_wrapper.scala.html
project/AppDependencies.scala
test/views/taxhistory/ConfirmDetailsViewSpec.scala

DDCE-3509 Account menu fixes

---

app/views/helpers/errorSummary.scala.html
app/views/taxhistory/select_tax_year.scala.html
project/AppDependencies.scala

DDCE-3513 Fix broken error link on Select Tax Year Page

---

README.md
app/controllers/SelectTaxYearController.scala
app/form/SelectClientForm.scala
app/views/taxhistory/select_client.scala.html
build.sbt
project/AppDependencies.scala
test/connectors/TaxHistoryConnectorSpec.scala
test/controllers/ClientErrorControllerSpec.scala
test/controllers/EmploymentDetailControllerSpec.scala
test/controllers/EmploymentSummaryControllerSpec.scala
test/controllers/SelectClientControllerSpec.scala
test/controllers/SelectTaxYearControllerSpec.scala
test/forms/SelectClientFormSpec.scala
test/model/api/AllowanceSpec.scala
test/model/api/StatePensionSpec.scala
test/model/api/TotalIncomeSpec.scala
test/support/ControllerSpec.scala
test/support/fixtures/ControllerFixture.scala
test/utils/MessagesSpec.scala
test/views/Fixture.scala
test/views/Strings.scala
test/views/errors/NoDataSpec.scala
test/views/models/PageTitleSpec.scala
test/views/taxhistory/Constants.scala
test/views/taxhistory/EmploymentDetailViewSpec.scala
test/views/taxhistory/EmploymentSummaryViewSpec.scala
test/views/taxhistory/SelectClientViewSpec.scala
test/views/taxhistory/SelectTaxYearViewSpec.scala

improve nino validation, + deps updates
To fix https://github.com/hmrc/accessibility-audits-external/issues/3724

DDCE-3442: improve nino validation, + deps updates

---

app/views/errors/no_agent_services_account.scala.html
build.sbt
conf/messages.cy
conf/messages.en
test/controllers/EmploymentDetailControllerSpec.scala
test/views/GovUkWrapperViewSpec.scala
test/views/errors/NoAgentServicesAccountViewSpec.scala
test/views/taxhistory/EmploymentDetailViewSpec.scala
test/views/taxhistory/SignedOutViewSpec.scala

- Fixed issue stated [here](https://github.com/hmrc/accessibility-audits-external/issues/3733)
- Test coverage bump
- Some cleanup done on this PR to avoid any conflicts. The cleanup that might cause conflicts are on another branch and would be raised separately

DDCE-3445 DAC retest issue - Missing Create account action, coverage & dependency bump + some cleanup

---

app/assets/stylesheets/taxhistory.scss
app/views/taxhistory/employment_detail.scala.html
app/views/taxhistory/employment_summary.scala.html
test/views/GovUkWrapperViewSpec.scala

Added wrapper to enable horizontal scrollbar on all tables on `employment_summary` and `employment_details`
Passes current ATs

DDCE-3448: Adjust tables to be responsive

---

a11y/FrontendAccessibilitySpec.scala
build.sbt
project/plugins.sbt
test/views/taxhistory/Constants.scala

sbt-accessibility-linter plugin runs and generates errors to be fixed in following ticket

DDCE-4267: Add sbt-accessibility-linter plugin

---

.gitignore
app/views/govuk_wrapper.scala.html
app/views/taxhistory/employment_summary.scala.html

Basically phase banner was the bulk of the issues. Decided to move it into <header> block and tried to centre it using class govuk-width-container
The other issue is role=list missing. So changed tablist into list.

DDCE-4395 Fix sbt linter errors
